apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "statuspage-chart.fullname" . }}-ingress
  labels:
    {{- include "statuspage-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: statuspage-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "statuspage-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
