apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "ly-statuspage-db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
  secretObjects:
    - secretName: db-secrets
      type: Opaque
      data:
        - objectName: "username"
          key: "username"
        - objectName: "password"
          key: "password"
