apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  parameters:
    objects: |
      - objectName: "ly-grafana-admin-password"
        objectType: "secretsmanager"
        jmesPath:
          - path: "password"
            objectAlias: "password"
          - path: "admin"
            objectAlias: "admin"
  provider: aws
  secretObjects:
  - data:
    - key: password
      objectName: password
    - key: admin
      objectName: admin
    secretName: monitoring-grafana
    type: Opaque

