apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: default
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::992382545251:role/statuspage-irsa-role
    meta.helm.sh/release-name: statuspage
    meta.helm.sh/release-namespace: default

