apiVersion: v1
kind: Service
metadata:
  name: {{ include "statuspage-chart.fullname" . }}
  labels:
    {{- include "statuspage-chart.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- if .Values.service.annotations }}
    {{- if has "service.beta.kubernetes.io/aws-load-balancer-ssl-cert" (keys .Values.service.annotations) }}
    - port: 443
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
    {{- end }}
    {{- end }}
  selector:
    {{- include "statuspage-chart.selectorLabels" . | nindent 4 }}
