apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: secrets-store-csi-driver-provider-aws
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: secrets-store-csi-driver-provider-aws
  template:
    metadata:
      labels:
        app: secrets-store-csi-driver-provider-aws
    spec:
      containers:
      - name: provider-aws
        image: public.ecr.aws/secrets-store-csi-driver/provider-aws:1.3.2
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
        volumeMounts:
        - name: providervol
          mountPath: "/etc/kubernetes/secrets-store-csi-providers"
      volumes:
      - name: providervol
        hostPath:
          path: "/etc/kubernetes/secrets-store-csi-providers"
          type: DirectoryOrCreate

