replicaCount: 2

metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"

image:
  repository: 992382545251.dkr.ecr.us-east-1.amazonaws.com/ly-statuspage-repo
  pullPolicy: Always
  tag: "v7"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:992382545251:certificate/3ad26a05-3441-4914-9589-5e638012949c"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"

ingress:
  enabled: false
  host: ly-statuspage.click

django:
  debug: false
  allowedHosts: "*"
  secretKey: "C2ldtKfBnOk-No8K4yTD4uAHKXmdii38hPzbEWuxRTERgRDPXkdT1MzmuRn9EKoW4Mc"
  database:
    host: ly-statuspage-rds.cx248m4we6k7.us-east-1.rds.amazonaws.com
    name: statuspage
    port: 5432
  redis:
    host: ly-statuspage-redis.7fftml.ng.0001.use1.cache.amazonaws.com
    port: 6379
    database: 0
    cachingDatabase: 1
  env:
    SITE_URL: "https://ly-statuspage.click"
    CSRF_TRUSTED_ORIGINS: "https://ly-statuspage.click,https://a53633fbafb76443d8806e929adf3f29-b13515d9f61dc082.elb.us-east-1.amazonaws.com"
    SECURE_SSL_REDIRECT: "true"
    SECURE_PROXY_SSL_HEADER: "HTTP_X_FORWARDED_PROTO,https"
    SECURE_HSTS_SECONDS: "31536000"
    SECURE_CONTENT_TYPE_NOSNIFF: "true"
    SECURE_BROWSER_XSS_FILTER: "true"
    USE_TZ: "true"
    DEBUG: "false"

serviceAccount:
  create: true
  automount: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::992382545251:role/statuspage-irsa-role
  name: "statuspage-sa"

resources:
  requests:
    memory: "1.5Gi"  # הקטן מ-1Gi
    cpu: "350m"      # הקטן מ-500m
  limits:
    memory: "2.5Gi"    # הקטן מ-3Gi  
    cpu: "750m"      # הקטן מ-1000m

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
