replicaCount: 2

metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"

image:
  repository: YOUR_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/ly-statuspage-repo
  pullPolicy: Always
  tag: "v1"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "YOUR_CERTIFICATE_ARN" # change to your ARN
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"

ingress:
  enabled: false
  host: your-domain # change to your domain

django:
  debug: false
  allowedHosts: "*"
  secretKey: "C2ldtKfBnOk-No8K4yTD4uAHKXmdii38hPzbEWuxRTERgRDPXkdT1MzmuRn9EKoW4Mc"
  database:
    host: your-RDS # change to your RDS endpoint
    name: statuspage
    port: 5432
  redis:
    host: your-redis # change to your redis endpoint
    port: 6379
    database: 0
    cachingDatabase: 1
  env:
    SITE_URL: "https://your domain" # change to your domain
    CSRF_TRUSTED_ORIGINS: "https://your-domain,https://a53633fbafb76443d8806e929adf3f29-b13515d9f61dc082.elb.us-east-1.amazonaws.com" # change to your elb and domain
    SECURE_SSL_REDIRECT: "true"
    SECURE_PROXY_SSL_HEADER: "HTTP_X_FORWARDED_PROTO,https"
    SECURE_HSTS_SECONDS: "31536000"
    SECURE_CONTENT_TYPE_NOSNIFF: "true"
    SECURE_BROWSER_XSS_FILTER: "true"
    USE_TZ: "true"
    DEBUG: "false"

serviceAccount:
  create: true
  automount: true
  annotations:
    eks.amazonaws.com/role-arn: "YOUR_IRSA_ROLE_ARN" # change
  name: "statuspage-sa"

resources:
  requests:
    memory: "1.5Gi"  
    cpu: "350m"   
  limits:
    memory: "2.5Gi"     
    cpu: "750m"      

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
